esproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('qa.urls')),
    path('admin/', admin.site.urls),
]

qa/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = 'qa'
urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('meu_perfil', views.meu_perfil, name='meu_perfil'),
    path('postar_pergunta', views.postar_pergunta, name='postar_pergunta'),
    path('listar_perguntas', views.listar_perguntas, name='listar_perguntas'),
    path('selecionar_pergunta/<int:pergunta_id>', views.selecionar_pergunta, name='selecionar_pergunta'),
    path('deletar_pergunta/<int:pergunta_id>', views.deletar_pergunta, name='deletar_pergunta'),
    path('alterar_pergunta/<int:pergunta_id>', views.alterar_pergunta, name='alterar_pergunta'),
    path('postar_resposta/<int:pergunta_id>', views.postar_resposta, name='postar_resposta'),
    path('selecionar_resposta/<int:resposta_id>', views.selecionar_resposta, name='selecionar_resposta'),
    path('alterar_resposta/<int:resposta_id>', views.alterar_resposta, name='alterar_resposta'),
    path('VotePergunta/<int:pergunta_id>', views.VotePergunta, name='VotePergunta'),
    path('VoteResposta/<int:pergunta_id>/<int:resposta_id>', views.VoteResposta, name='VoteResposta'),
    path('deletar_resposta/<int:resposta_id>', views.deletar_resposta, name='deletar_resposta'),
    path('cadastrar_usuario', TemplateView.as_view(template_name='qa/cadastrar_usuario.html'), name='cadastrar_usuario'),

    path('registrar_usuario', views.registrar_usuario, name='registrar_usuario'),
    path('login_usuario', views.login_usuario, name='login_usuario'),
    path('logout_usuario', views.logout_usuario, name='logout_usuario'),
    path('logged', views.logged, name='logged'),
    path('meus_posts', views.meus_posts, name='meus_posts'),
    path('remover_usuario', views.remover_usuario, name='remover_usuario'),
    
    path('tags/<str:tag>', views.detalha_tag, name='detalhaTag'),
]

qa/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    instituicao = models.CharField(max_length=100, blank=True)
    profissao = models.CharField(max_length=100, blank=True)
    descricao = models.TextField(max_length=1000, blank=True)
    def __str__(self):
        return self.user.username

class Pergunta(models.Model):
    usuario = models.CharField(max_length=100, default='usuario default')
    titulo = models.CharField(max_length=100, blank=True)
    texto = models.TextField(max_length=1000, default='texto default')
    #A lista de Tags será guardada como uma String JSON serializado.
    tags = models.TextField(null=True)
    votos = models.IntegerField(default=0)
    def __str__(self):
        return self.titulo

class Resposta(models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    usuario = models.CharField(max_length=100)
    texto = models.CharField(max_length=1000)
    votos = models.IntegerField(default=0)
    def __str__(self):
        return self.texto

class VotosPerguntas(models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    usuario = models.CharField(max_length=100)
    def __str__(self):
        return self.usuario

class VotosRespostas(models.Model):
    resposta = models.ForeignKey(Resposta, on_delete=models.CASCADE)
    usuario = models.CharField(max_length=100)
    def __str__(self):
        return self.usuario

qa/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class ProfileForm(forms.ModelForm):
     class Meta():
         model = Profile
         fields = ('instituicao', 'profissao', 'descricao')

qa/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect

from .forms import UserForm, ProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .models import Pergunta, Resposta, Profile, VotosPerguntas, VotosRespostas

import json

def home(request):
    if request.user.is_authenticated:
        usuario = request.user.get_username()
    else:
        usuario = None
    context = {'usuario': usuario}
    return render(request, 'qa/home.html', context)

# responsavel por salvar a pergunta no BD
def postar_pergunta(request):
    usuario = request.user.get_username()
    if request.method == 'POST':
        try:
            tagsString = request.POST['tags']
            tagsList = tagsString.split(',')
            for i in range(len(tagsList)):
                tagsList[i] = tagsList[i].strip()
            if tagsList[-1]=='':
                tagsList.pop()
            tagsJson = json.dumps(tagsList)
            pergunta = Pergunta(usuario=usuario, titulo=request.POST['titulo'], texto=request.POST['texto'], tags = tagsJson, votos = 0)
            pergunta.save()
        except (KeyError, pergunta.pk == None):
            msg = 'Sua pergunta não foi postada'
            context = {'usuario':usuario, 'msg': msg, 'sucesso':False}
            return render(request, 'qa/postar_pergunta.html', context)
        msg = 'Sua pergunta foi postada'
        context = {'usuario':usuario, 'msg': msg, 'sucesso':True}
        return render(request, 'qa/postar_pergunta.html', context)
    else:
        context = {"usuario": usuario}
        return render(request, 'qa/postar_pergunta.html', context)
    
# renderiza html com a lista de perguntas ja feitas
def listar_perguntas(request):
    usuario = request.user.get_username()
    perguntas = Pergunta.objects.all()
    context = {'perguntas': perguntas, 'usuario':usuario}
    return render(request, 'qa/lista_perguntas.html', context)

# busca pergunta selecionada no BD e renderiza o html com informacoes dela
def selecionar_pergunta(request, pergunta_id):
    usuario = request.user.get_username()
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
    lista_respostas = pergunta.resposta_set.all()  
    jsonDec = json.decoder.JSONDecoder()
    tagsList = jsonDec.decode(pergunta.tags)
    tagsString = ''
    for i in tagsList:
    	tagsString = tagsString+i+','
    VotosTotais = VotosPerguntas.objects.all()
    VotosTotaisRespostas = VotosRespostas.objects.all()
    context = {'VotosTotaisRespostas': VotosTotaisRespostas, 'pergunta': pergunta,'tags': tagsString,'tagsList':tagsList, 'lista_respostas': lista_respostas, 'usuario':usuario, "VotosTotais": VotosTotais}    
    return render(request, 'qa/pergunta_selecionada.html', context)

# responsavel por deletar a pergunta selecionada do BD
def deletar_pergunta(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
    try:
        pergunta.delete()
        msg = "Pergunta deletada com sucesso!"
        sucesso = True
    except (KeyError, pergunta.pk != None):
        msg = "Erro ao deletar pergunta!"
        sucesso = False
    context = {'msg': msg, 'sucesso':sucesso}
    return render(request,'qa/home.html', context)

# responsavel por alterar o texto da pergunta selecionada no BD
def alterar_pergunta(request, pergunta_id):
    pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
    
    tagsString = request.POST['tags_alterado']
    tagsList = tagsString.split(',')
    for i in range(len(tagsList)):
        tagsList[i] = tagsList[i].strip()
    if tagsList[-1]=='':
        tagsList.pop()
    tagsJson = json.dumps(tagsList)
    
    pergunta.titulo = request.POST['titulo_alterado']
    pergunta.texto = request.POST['texto_alterado']
    pergunta.tags = tagsJson
    pergunta.save()
    context = {'pergunta': pergunta}
    return HttpResponseRedirect("/selecionar_pergunta/%s" % (pergunta_id))   

# responsavel por salvar a resposta no BD
def postar_resposta(request, pergunta_id):
    if request.method == 'POST':
        if request.user.is_authenticated:
            usuario = request.user.get_username()
            pergunta = get_object_or_404(Pergunta, pk=pergunta_id)
            try:
                resposta = pergunta.resposta_set.create(usuario=usuario, texto=request.POST['texto'])
            except (KeyError):
                context = {'msg': "Resposta não foi salva", 'sucesso':False}
                return render(request,'qa/home.html', context)
            return HttpResponseRedirect('/selecionar_pergunta/%s' % (pergunta.id))
        else:
            return HttpResponse("Voce precisa estar logado para postar uma resposta")

# busca pergunta selecionada no BD e renderiza o html com informacoes dela
def selecionar_resposta(request, resposta_id):
    usuario = request.user.get_username()
    resposta = get_object_or_404(Resposta, pk=resposta_id)
    pergunta = get_object_or_404(Pergunta, pk=resposta.pergunta.id)
    
    jsonDec = json.decoder.JSONDecoder()
    tagsList = jsonDec.decode(pergunta.tags)
    
    if request.method  == 'POST':
        resposta.texto = request.POST['texto_alterado']
        resposta.save()
        context = {'resposta': resposta, 'usuario': usuario,'tagsList':tagsList}    
        return HttpResponseRedirect('/selecionar_resposta/%s' % (resposta_id))
    else:
        context = {'pergunta': pergunta, 'resposta': resposta, 'usuario': usuario,'tagsList':tagsList}    
        return render(request, 'qa/resposta_selecionada.html', context)

# responsavel por deletar a pergunta selecionada do BD
def deletar_resposta(request, resposta_id):
    resposta = get_object_or_404(Resposta, pk=resposta_id)
    try:
        resposta.delete()
        msg = "Resposta deletada com sucesso!"
        sucesso = True
    except (KeyError, resposta.pk != None):
        msg = "Resposta nao foi deletada"
        sucesso = False
    context = {'msg': msg, 'sucesso':sucesso}
    return render(request,'qa/home.html', context)

# responsavel por alterar o texto da pergunta selecionada no BD
def alterar_resposta(request, resposta_id):
    resposta = get_object_or_404(Resposta, pk=resposta_id)
    resposta.texto = request.POST['texto_alterado']
    resposta.save()
    return HttpResponseRedirect('/selecionar_resposta/%s' %(resposta_id))

def logged(request):
    if request.user.is_authenticated:
        context = {'msg': "Você está logado", 'sucesso':True}
        return render(request,'qa/home.html', context)
    else:
        context = {'msg': "Você não está logado", 'sucesso':True}
        return render(request,'qa/home.html', context)

def login_usuario(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect('/home')
            else:
                msg = 'Usuário inativo'
                context = {'msg':msg, 'sucesso': False}
                return render(request, 'qa/login.html', context)
        else:
            msg = 'Usuário ou senha incorretos'
            context = {'msg':msg, 'sucesso': False}
            return render(request, 'qa/login.html', context)
    else:
         return render(request, 'qa/login.html')

def logout_usuario(request):
    if request.user.is_authenticated:
        logout(request)
        return HttpResponseRedirect('/home')
    else:
        context = {'msg': "Você não está logado", 'sucesso':False}
        return render(request,'qa/home.html', context)
        

def registrar_usuario(request):
    # Retirado o userInfo
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_profile = ProfileForm(data=request.POST)
        if user_form.is_valid() and user_profile.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = user_profile.save(commit=False)
            profile.user = user
            profile.save()
            return HttpResponseRedirect('/login_usuario')
        else:
            print(user_form.errors)
            context = {'msg': "Não registrado"}
            return render(request,'qa/cadastro.html', context)
    else:
        user_form = UserForm()
        return render(request, 'qa/cadastro.html')

def meu_perfil(request):
    if request.method == 'POST':
        new_password = request.POST['new_password']
        username = request.user.get_username()
        email = request.POST['email']
        instituicao = request.POST['instituicao']
        profissao = request.POST['profissao']
        descricao = request.POST['descricao']
        user = request.user
        if new_password != '':
            user.set_password(new_password)
            user.save()
            login(request,user)

        profile = Profile.objects.get(user=request.user)
        user.email=email
        user.save()
        profile.instituicao = instituicao
        profile.profissao = profissao
        profile.descricao = descricao
        user.save()
        profile.save()
        return HttpResponseRedirect('/meu_perfil')
    else:
        usuario = request.user.get_username()
        if usuario:
            email = request.user.email
            profile = Profile.objects.get(user=request.user)
            context = {'usuario':usuario, 'email':email, 'profissao':profile.profissao, 'instituicao':profile.instituicao, 'descricao':profile.descricao}
            return render(request, 'qa/meu_perfil.html', context)
        return render(request, 'qa/meu_perfil.html')

# renderiza html com a lista de perguntas ja feitas
def meus_posts(request):
    usuario = request.user.get_username()
    perguntas = None
    respostas = None

qa/templates/qa/meu_perfil.html
{% extends 'qa/template.html' %}
{% block content %}
    <style>
        .full-width{
            width: 100%;
        }
        .prepend-width{
            width: 150px;
        }
    </style>
    <div class='container-fluid ml-4 mt-3'>
        <h4>Perfil do Usuário</h4>
        {% if usuario %}
        
            <form action='{% url "qa:meu_perfil" %}' method='post'>
                {% csrf_token %}
                <div class='col-11 mt-3 ml-3 pl-0'>
                    <div class='row'>
                        <div class="input-group mb-3 col-6 pl-0">
                            <div class="input-group-prepend prepend-width">
                                <div class="input-group-text full-width justify-content-center">
                                    Usuário
                                </div>
                            </div>
                            <input type='text' name='username' class="form-control bg-light" value='{{usuario}}' disabled/>
                        </div>

                        <div class="input-group mb-3 col-6 pr-0">
                            <div class="input-group-prepend prepend-width">
                                <div class="input-group-text full-width justify-content-center">
                                    Email
                                </div>
                            </div>
                            <input type='text' name='email' class="form-control" value='{{email}}'/>
                        </div>

                        <div class="input-group mb-3 col-6 pl-0">
                            <div class="input-group-prepend prepend-width">
                                <div class="input-group-text full-width justify-content-center">
                                    Nova Senha
                                </div>
                            </div>
                            <input type='password' name='new_password' id='new_password' class="form-control" autocomplete="new-password"/>
                        </div>

                        <div class="input-group mb-3 col-6 pr-0">
                            <div class="input-group-prepend prepend-width">
                                <div class="input-group-text full-width justify-content-center">
                                    Instituição
                                </div>
                            </div>
                            <input type='text' name='instituicao' class="form-control" value='{{instituicao}}'/>
                        </div>

                        <div class="input-group mb-3 col-6 pl-0">
                            <div class="input-group-prepend prepend-width">
                                <div class="input-group-text full-width justify-content-center">
                                    Confirme a senha
                                </div>
                            </div>
                            <input type='password' id='new_password2'  class="form-control"/>
                        </div>

                        <div class="input-group mb-3 col-6 pr-0">
                            <div class="input-group-prepend prepend-width">
                                <div class="input-group-text full-width justify-content-center">
                                    Profissão
                                </div>
                            </div>
                            <input type='text' name='profissao' class="form-control" value='{{profissao}}'/>
                        </div>

                        <div class="input-group mb-3">
                            <div class="input-group-prepend prepend-width">
                                <div class="input-group-text full-width justify-content-center">
                                    Descrição
                                </div>
                            </div>
                            <textarea class="form-control col-12" rows="5" name='descricao'>{{descricao}}</textarea>
                        </div>

                        <div class="input-group mb-2 justify-content-center">
                            <input type='submit' class="btn bg-success col-3 mr-1 text-light" value='Salvar Alterações' id='alteracoesSubmit'/>
                            <input type='button' class="btn bg-danger col-3 ml-1 text-light" value='Excluir Conta' data-toggle='modal' data-target='#confirmDeletar'/>
                        </div>
                    </div>
                </div>
            </form>
                
            <!-- The Modal -->
            <div class="modal" id="confirmDeletar" style='padding-right: 0px !important'>
                <div class="modal-dialog" style='top: 25%; left: 8.7%'>
                    <div class="modal-content" style='box-shadow: 0px 0px 20px 10px #aaaaaa;'>
                        <!-- Modal Header -->
                        <div class="modal-header py-3">
                            <h4 class="modal-title">Confirme sua senha</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        
                        <!-- Modal body -->
                        <div class="modal-body p-0">
                            <form action='{% url "qa:remover_usuario" %}' method='post'>
                                {% csrf_token %}
                                <div class="input-group mb-3 mx-auto col-9">
                                    <input type='password' name='password' class="form-control" placeholder="Senha"/>
                                    <div class="input-group-append">
                                        <input type='submit' class="btn bg-danger text-light" value='Excluir Conta' id='deletarSubmit'/>
                                    </div>
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>

            <script>
                $('#alteracoesSubmit').click(function(e){
                    if($('#new_password').val() === $('#new_password2').val()) {
                        
                    } else {
                        e.preventDefault();
                        alert('Senhas nao coincidem');
                    }
                });
            </script>
        
        {% else %}
        <span class='mt-3'>
            É preciso fazer <a href='/login_usuario'>Login</a> para visualizar seu perfil.
        </span>
        {% endif %}
    </div>
{% endblock %}

qa/templates/qa/pergunta_selecionada.html
{% extends 'qa/template.html' %}

{% block content %}
	<style>
        .full-width{
            width: 100%;
        }
        .prepend-width{
            width: 100px;
        }
    </style>
	<div class='container-fluid ml-4 mt-3'>
		<div class='row ml-0'>
			<h5>Pergunta Selecionada</h5>
		</div>
		<div class='row'>
			<div class='col-11'>
				<div class="input-group mb-2 pl-0 col-4">
					<div class="input-group-prepend prepend-width">
						<div class="input-group-text full-width justify-content-center">
							Usuário
						</div>
					</div>
					<input type='text' name='username' class="form-control bg-light" value='{{pergunta.usuario}}' disabled/>
				</div>
				<div class="input-group mb-2">
					<div class="input-group-prepend prepend-width">
						<div class="input-group-text full-width justify-content-center">
							Titulo
						</div>
					</div>
					<input type='text' id="perguntaTitulo" class="form-control col-12 bg-light" name='titulo' value='{{pergunta.titulo}}'/>
				</div>
				<div class="input-group mb-2">
					<div class="input-group-prepend prepend-width">
						<div class="input-group-text full-width justify-content-center">
							Pergunta
						</div>
					</div>
					<textarea id="perguntaTexto" class="form-control col-12 bg-light" name='texto' rows='2'>{{pergunta.texto}}</textarea>
				</div>
				<div class="input-group">
                        <div class="input-group-prepend prepend-width">
                            <div class="input-group-text full-width justify-content-center">
                                Tags
                            </div>
                        </div>
                        <textarea id="perguntaTags" class="form-control col-12" rows="3" name="tags" placeholder="Digite as tags separadas por vírgulas." required>{{tags}}</textarea>
                    </div>
					<form id='formUpVote' action='{% url "qa:VotePergunta" pergunta.id %}' method='post'>
					<div class="input-group">
						<div class="input-group-prepend prepend-width">
							<div class="input-group-text full-width justify-content-center">
								Votos
							</div>
						</div>
						
							{% csrf_token %}
							<textarea id="votos" class="form-control col-2 bg-light" name='votos' rows='1'>{{pergunta.votos}}</textarea>
							{% if usuario %}
							<input id='upVote' type='button' value='Up' class='btn bg-success px-2 text-light'/>
							<input id='downVote' type='button' value='Down' class='btn bg-danger px-2 text-light'/>
							{% if VotosTotais %}
								{% for voto in VotosTotais %}
									{% if voto.pergunta == pergunta and voto.usuario == usuario %}
										<script>
											$('#upVote').attr('disabled', true);
											$('#downVote').attr('disabled', true);
										</script>
									{% endif %}
								{% endfor %}
							{% endif %}
							<script>
								$("#upVote").click(function(){
									$('#upVote').attr('disabled', true);
									$('#downVote').attr('disabled', true);
									votosAtuais = parseInt($('#votos').val())
									votosAlterados = votosAtuais + 1
									$("#votos").val(votosAlterados.toString(10));
									$("#formUpVote").submit();
								});
							</script>
							<script>
								$("#downVote").click(function(){
									$('#upVote').attr('disabled', true);
									$('#downVote').attr('disabled', true);
									votosAtuais = parseInt($('#votos').val())
									votosAlterados = votosAtuais - 1
									$("#votos").val(votosAlterados.toString(10));
									$("#formUpVote").submit();
								});
							</script>
							{% endif %}
					</div>
					</form>
				{% if usuario != pergunta.usuario %}
				<script>
					$('#perguntaTitulo').attr('disabled', true);
					$('#perguntaTexto').attr('disabled', true);
					$('#perguntaTags').attr('disabled', true);
				</script>
				{% endif %}
				{% if usuario == pergunta.usuario %}
					<div class='row ml-0 mt-2 justify-content-center'>
						<form id='formAlterarPergunta' action='{% url "qa:alterar_pergunta" pergunta.id %}' method='post'>
							<input hidden id='texto_alterado' name='texto_alterado' required/>
							<input hidden id='titulo_alterado' name='titulo_alterado' required/>
							<input hidden id='tags_alterado' name='tags_alterado' required/>
							{% csrf_token %}
							<input type='button' id='alterarPerguntaBtn' class='btn btn-success py-1 mr-1' value='Alterar pergunta'/>
							<script>
								$("#alterarPerguntaBtn").click(function(){
									titulo_alterado = $('#perguntaTitulo').val()
									texto_alterado = $('#perguntaTexto').val()
									tags_alterado = $('#perguntaTags').val()
									$('#titulo_alterado').val(titulo_alterado)
									$('#texto_alterado').val(texto_alterado)
									$('#tags_alterado').val(tags_alterado)
									$("#formAlterarPergunta").submit();
								});
							</script>
						</form>
						<form action='{% url "qa:deletar_pergunta" pergunta.id %}' method='post'>
							{% csrf_token %}
							<input type='submit' class='btn btn-danger py-1 ml-1' value='Deletar pergunta'/>
						</form>
					</div>
				{% endif %}
			</div>
		</div>
		<hr class='mr-5'/>
		<div class='row ml-0'>
			<h5>Tags</h5>
		</div>
		<div class='col-11 pl-0 mb-1 pt-1' style='height:auto; max-height: 32vh; overflow:auto'>
		
			{% for tag in tagsList %}
				<a href="/tags/{{tag}}">{{tag}}</a>,
			{% endfor %}
		</div>
		<hr class='mr-5'/>
		<div class='row ml-0'>
			<h5>Respostas</h5>
		</div>
		{% if lista_respostas %}
		<div class='row ml-0'>
			<div class='col-11 pl-0 mb-1 pt-1' style='height:auto; max-height: 32vh; overflow:auto'>
				{% for resposta in lista_respostas %}
					<div class='container mb-2' style='box-shadow: 0px 0px 1px 0.1px #aaaaaa; margin-left: 1px'>
						<a class='nolink' href='/selecionar_resposta/{{resposta.id}}'>
							<div class='row'>
								<div class='col-6'>
									resposta #{{forloop.counter}}
								</div>
								<div class='col-6 text-right'>
									autor: {{resposta.usuario}}
								</div>
							</div>
							<div class='row border-top'>
								<div class='col-12'>
									<p>{{resposta.texto}}</p>
								</div>
							</div>
						</a>
						<div class='row border-top'>
							<form id='formUpVoteResposta{{resposta.id}}' action='{% url "qa:VoteResposta" pergunta.id resposta.id %}' method='post'>
							{% csrf_token %}
							<div class='input-group'>	
								<textarea id="votosResposta{{resposta.id}}" class="form-control col-3 bg-light" name='votosResposta{{resposta.id}}' rows='1'>{{resposta.votos}}</textarea>
								{% if usuario %}
								<input id='upVoteResposta{{resposta.id}}' type='button' value='Up' class='btn bg-success px-2 text-light'/>
								<input id='downVoteResposta{{resposta.id}}' type='button' value='Down' class='btn bg-danger px-2 text-light'/>
								{% endif %}
							</div>
							{% if usuario %}
								{% if VotosTotaisRespostas %}
									{% for voto in VotosTotaisRespostas %}
										{% if voto.resposta == resposta and voto.usuario == usuario %}
											<script>
												$('#upVoteResposta{{resposta.id}}').attr('disabled', true);
												$('#downVoteResposta{{resposta.id}}').attr('disabled', true);
											</script>
										{% endif %}
									{% endfor %}
								{% endif %}
							{% endif %}
							<script>
								$("#upVoteResposta{{resposta.id}}").click(function(){								
									$('#upVoteResposta{{resposta.id}}').attr('disabled', true);
									$('#downVoteResposta{{resposta.id}}').attr('disabled', true);
									votosAtuais = parseInt($('#votosResposta{{resposta.id}}').val())
									votosAlterados = votosAtuais + 1
									$("#votosResposta{{resposta.id}}").val(votosAlterados.toString(10));
									$("#formUpVoteResposta{{resposta.id}}").submit();
								});
							</script>
							<script>
								$("#downVoteResposta{{resposta.id}}").click(function(){
									$('#upVoteResposta{{resposta.id}}').attr('disabled', true);
									$('#downVoteResposta{{resposta.id}}').attr('disabled', true);
									votosAtuais = parseInt($('#votosResposta{{resposta.id}}').val())
									votosAlterados = votosAtuais - 1
									$("#votosResposta{{resposta.id}}").val(votosAlterados.toString(10));
									$("#formUpVoteResposta{{resposta.id}}").submit();
								});
							</script>
							</form>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
        {% endif %}

		<hr class='mr-5'/>
		<div class='row ml-0'>
			<h5>Postar Resposta</h5>
		</div>
		<div class='row ml-0 mb-4'>
			<div class='col-11 px-0'>
				<form action='{% url "qa:postar_resposta" pergunta.id %}' method='post'>
					{% csrf_token %}
					<div class="form-group mb-0">
						<textarea id='respostaTexto' class="form-control col-12 bg-light" rows="5" name='texto' required></textarea>
					</div>
					<div class='row mt-2 mx-auto justify-content-end'>
						<input id='respostaSubmit' type='submit' value='Postar Resposta' class='btn bg-success px-5 text-light'/>
					</div>
					<script>
						function closeAlertBox(){
							alertBox = document.getElementById("alertBox");
							alertClose = document.getElementById("alertClose");
							alertBox.style.visibility = "hidden";
							alertClose.style.visibility = "hidden";
						}
						window.alert = function(msg){
							var id = "alertBox", alertBox, closeId = "alertClose", alertClose;
							alertBox = document.createElement("div");
							document.body.appendChild(alertBox);
							alertBox.id = id;
							alertBox.innerHTML = msg;
							alertClose = document.createElement("div");
							alertClose.id = closeId;
							alertClose.innerHTML = "x";
							alertBox.appendChild(alertClose);
							alertBox.style.visibility = "visible";
							alertClose.style.visibility = "visible";
							alertClose.onclick = closeAlertBox;
							alertBox.style.left = "1140px";
							if(sucesso == false)
							{
								document.getElementById('alertBox').style.backgroundColor = 'red'
							}
						};
						if ('{{usuario}}' === ''){
							flagUser = false
						}
						
						$('#respostaTexto').click(function(e){
							if(flagUser === false){
								$('#respostaTexto').attr('disabled', true)
								sucesso = false
								alert('Precisa Estar logado');
							}
						});

						$('#respostaSubmit').click(function(e){
							if(flagUser === false){
								e.preventDefault();
								sucesso=false;
								alert('Precisa Estar logado');
							}
						});
					</script>
				</form>
			</div>
		</div>
    </div>
{% endblock %}